Repository eclipse-birt/birt, pull requests merged in 2024-10, with the labels that each got.

#1928 Fix the correct PPTX handling of hyperlink decoration
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
Labels: BugFix

#1931 Fix documentation and eclipse warnings
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/page/TextPage.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editparts/LabelEditPart.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/figures/LabelFigure.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/figures/TextFlow.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/EmitterContext.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/WordUtil.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/EmitterUtil.java
Labels: Documentation

#1936 Fix the ampersand of validation messages on the dataset editor (#1935)
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
  UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/PropertyHandleInputDialog.java
Labels: BugFix

#1942 Enhance the docx emitter to add padding calculation to BIRT element "label" (#1941)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
Labels: Enhancement

#1953 Fix PDF syntax error (cm not allowed after BT)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
Labels: BugFix

#1956 Excel, force automated column width calculation if streaming mode of XLSX is enabled (#1955)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
Labels: BugFix
