Repository eclipse-birt/birt, pull requests merged in 2024-11, with the labels that each got.

#1958 Optimization of docx emitter output (#1957)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/DocxEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/DocEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/EmitterServices.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/WordUtil.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/DocWriter.java
Labels: Feature

#1961 Feature for DOCX to add standard border handling of (dynamic) text (#1957)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/EmitterUtil.java
Labels: Enhancement

#1964 Documentation for the word emitter user properties like readme (#1957)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/README.md
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
Labels: Documentation

#1966 Label element recognize the configuration of padding & margin calculation (#1965)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/EmitterServices.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
Labels: Enhancement

#1970 The designer advanced register provide the configuration for the word layout (#1969)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/DocxEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Document.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Footer.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Header.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/EmitterServices.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/README.md
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: Enhancement, BugFix

#1974 Optimize method getProperty and replace the thrown RuntimeException through a null value as return value (#1975)
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/core/DesignElement.java
Labels: Enhancement

#1976 DOCX: create the correct word structure if the foreign content is empty (#1975)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
Labels: BugFix

#1978 JavaScript, editor gets additional object highlighting (#1977)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
Labels: Enhancement

#1980 Fix DOCX calculation of margin and padding (#1979)
  engine/org.eclipse.birt.report.engine.emitter.prototype.excel/src/org/eclipse/birt/report/engine/emitter/excel/ExcelUtil.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/WordUtil.java
Labels: BugFix

#1982 Enhance display text for multi selections (#1981)
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/service/ReportEngineService.java
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/BirtUtility.java
Labels: Enhancement

#1972 Preliminary PDF/UA support
  UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/Accessibility/complexTable.rptdesign
  UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/Accessibility/headings_images.rptdesign
  UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/Accessibility/hello_world.rptdesign
  UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/Accessibility/sonne.png
  UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/Accessibility/table.rptdesign
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFRender.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
  engine/org.eclipse.birt.report.engine/META-INF/MANIFEST.MF
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/ICellContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/IContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/ITextContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/AbstractContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/CellContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/LabelItemExecutor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ReportItemExecutor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/internal/content/wrap/AbstractContentWrapper.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/emitter/PageDeviceRender.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/cache/ClonedCellContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/HTML2Content.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/RegionLayoutEngine.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/IContainerArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/ITagType.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/BlockContainerArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/BlockTextArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ContainerArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ImageAreaLayout.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/InlineContainerArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/PageArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/RegionArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/RootArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/EngineIRVisitor.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/DesignElementHandle.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/RowHandle.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/util/StringUtil.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/strategy/ReportItemPropSearchStrategy.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: Help wanted, Enhancement
