Repository eclipse-birt/birt, pull requests merged in 2024-05, with the labels that each got.

#1661 Enhance the support of text line-through for excel (#1660)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/FontManager.java
Labels: Enhancement

#1667 Enhance the excel output to get the formatting option of text-indent (#1666)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/BirtStyle.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ClientAnchorConversions.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManager.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
Labels: Enhancement

#1671 Fix eclipse warnings and add java documentation (#1670)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/BIRTCSSEngine.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSContext.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSEngine.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSStylableElement.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/PerfectHash.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/PropertyManagerFactory.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/SystemColorSupport.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/ValueManager.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CSSValue.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssParser.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyle.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheet.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheetAdapter.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheetHandleAdapter.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/Property.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleDeclaration.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleRule.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleSheetLoader.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/property/PropertyParser.java
Labels: Documentation

#1673 Fix the structure of "drawstreamimage" on "header.ps"-file by edding an "end" (#1669)
  engine/org.eclipse.birt.report.engine.emitter.postscript/src/org/eclipse/birt/report/engine/emitter/postscript/header.ps
Labels: BugFix

#1674 Fix eclipse warnings and add java documentation, part 2 (#1670)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/ICellContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/IReportContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/dom/AbstractStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/dom/ComputedStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/AbstractColorManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/AbstractLengthManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/AbstractValueFactory.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/AbstractValueManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/DataFormatValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/FloatValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/IdentifierManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/ListValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/RGBColorValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/RectValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/StringMap.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/StringValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/URIValue.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/Value.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/css/URIManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/buffermgr/Cell.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/buffermgr/Row.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/buffermgr/Table.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/buffermgr/TableContentLayout.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/ir/ReportItemDesign.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/ir/TextItemDesign.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/ir/VisibilityDesign.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/StyleUtil.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/TableItemDesignLayout.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/TextParser.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/presentation/LocalizedContentVisitor.java
Labels: Documentation

#1678 Fix BIRT-designer, replaced XYLayout and XYLayoutEditPolicy (#1665)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/rulers/EditorRulerLayout.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editparts/TableEditPart.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editpolicies/TableXYLayoutEditPolicy.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/layout/TableLayout.java
Labels: BugFix

#1681 Fix the missing Refresh-Button of DataBinding-dialog (#1680)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/DataSetColumnBindingsFormPage.java
Labels: BugFix

#1682 Enhancement to add ECMAScript 6 support (#1574)
  UI/org.eclipse.birt.report.designer.ui/META-INF/MANIFEST.MF
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/ScriptValidator.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngine.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptVersion.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/README.md
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/IDesignSchemaConstants.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/VersionUtil.java
Labels: Enhancement

#1685 Enhance the syntax highlighting of ECMAScript 6 (#1684)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
Labels: Enhancement

#1690 Enhance syntax highlights with additional values (#1684)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
Labels: Enhancement

#1687 Fix of excel column width calculation (#1686)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ClientAnchorConversions.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
Labels: BugFix

#1694 Enhance syntax highlights for object members (#1684)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
Labels: Enhancement

#1696 Enhance the sql syntax highlighting of query editor (#1695)
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/utils/ISQLSyntax.java
Labels: Enhancement

#1697 Corrected eclipse warnings and added comments (#1695)
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/JdbcSQLContentAssistProcessor.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/OdaConnectionProvider.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLDataSetEditorPage.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLKeywordRule.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLKeywordScanner.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLPartitionScanner.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLSourceViewerConfiguration.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLUtility.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/TextMenuManager.java
Labels: Documentation

#1701 Enhance the SQL-dataset-editor with a search option (#1700)
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLDataSetEditorPage.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/SQLSourceViewer.java
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/nls/JdbcPluginResources.properties
Labels: Feature

#1706 Restore the original sorting of the 3rd view for the expression builder (#1699)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ExpressionBuilder.java
Labels: BugFix

#1704 do not autosize columns in case of StreamingXlsx eclipse-birt#1703
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
Labels: BugFix

#1708 Fix number format for "lakhs" format based on com.ibm.icu.text.* (#1672)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/FormatNumberLayoutPeer.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/CascadingParametersDialog.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ParameterDialog.java
  core/org.eclipse.birt.core/src/org/eclipse/birt/core/format/NumberFormatter.java
  engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/test/org/eclipse/birt/report/engine/dataextraction/csv/testDataTypesLocalized.csv
  engine/org.eclipse.birt.report.engine.dataextraction.csv/src/org/eclipse/birt/report/engine/dataextraction/csv/CSVDataExtractionImpl.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/FloatValue.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/metadata/FloatPropertyType.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/DimensionValueUtil.java
  testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/api/GroupHandleTest.java
  testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_102725.java
Labels: BugFix
