Repository eclipse-birt/birt, pull requests merged in 2024-12, with the labels that each got.

#1994 BIRT OSGi, copy org.apache.commons.commons-logging to the lib-folder
  build/birt-packages/birt-runtime-osgi/build.xml
Labels: Releng

#2000 BIRT constants add documentation and fix eclipse warnings
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/IBirtConstants.java
Labels: Documentation

#2003 Enhance the web application start page to optimize handling and information set
  viewer/org.eclipse.birt.report.viewer/birt/index.jsp
Labels: Enhancement

#2004 Enhance start page of web application and added BIRT homepage and project link (#2002)
  viewer/org.eclipse.birt.report.viewer/birt/index.jsp
Labels: Enhancement

#2005 How to apply dataset filter expression while get parameter selection …
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IGetParameterDefinitionTask.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/GetParameterDefinitionTask.java
Labels: Enhancement

#2006 Enhanced documentation of the interface change "IGetParameterDefinitionTask" (#2005)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IGetParameterDefinitionTask.java
Labels: Documentation

#2007 Enhance the HTML border handling for style scripting (#2001)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/AttributeBuilder.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
Labels: Enhancement

#2011 Fix the docx issue with grid in grid to setup the old wpml behavior (add empty paragraphs) as default (#2010)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/DocEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/EmitterServices.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/README.md
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/IDesignSchemaConstants.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/VersionUtil.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: BugFix

#2013 Fix to avoid preview error for incorrect parameters (#2012)
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/service/BirtViewerReportService.java
Labels: BugFix

#2015 Enhance pptx to support document bookmarks for images (#1991)
  engine/org.eclipse.birt.report.engine.emitter.ppt/src/org/eclipse/birt/report/engine/emitter/ppt/util/PPTUtil.java
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
Labels: Enhancement
