Repository eclipse-birt/birt, pull requests merged in 2024-08, with the labels that each got.

#1823 Enhance the PDF options to provide the control option to include the CIDSet of a font (#1817)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
Labels: Enhancement

#1827 Enhance the JDBC Driver Manager to validate all driver supported properies (JDBC-driver, #1825)
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/JDBCDriverManager.java
Labels: Enhancement

#1831 Improve java doc and remove warnings of the driver manager (#1825)
  data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/util/DriverLoader.java
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/JDBCDriverManager.java
Labels: Documentation

#1833 Enhanced JDBC driver manager with configuration based on new JVM parameters (#1832)
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/JDBCDriverManager.java
Labels: Enhancement

#1838 Documentation of the JDBC connection property validation
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/README.md
Labels: Documentation

#1840 Enhance java documentation and remove java warnings of HTML2PDF layout
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/script/IReportContext.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/BulletFrame.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/HTML2Content.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/HTMLConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/HTMLStyleProcessor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/PropertiesProcessor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/ShortHandProcessor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/StyleProperties.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/Tag2Style.java
Labels: Documentation

#1842 Improve the description of the README.MD
  data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/README.md
Labels: Documentation

#1845 Enhance the designer to add the PDF emitter options like configuration at advanced property register (#1844)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: Enhancement

#1846 Adjust the PDF.emitter REAMDME.md and optimized the documentation (#1844)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
Labels: Documentation

#1857 Enhance of SVG-converting for PDF based on external resources (#1841)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
Labels: Enhancement

#1856 Fix the NPE of images without wrapping grid/table (#1855)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/CellImage.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
Labels: BugFix

#1861 Simplify the org.eclipse.birt.engine.runtime product
  build/birt-packages/birt-runtime-osgi/reportengine.product
Labels: Dependencies

#1871 Fix hidden antidiagonal line of merged cells (#1870)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerXUtils.java
Labels: BugFix

#1869 Fix the word column width which is larger like 22in (#1867)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/WordUtil.java
Labels: BugFix

#1873 Fix the display of diagonals if the style is unset (#1872)
  engine/org.eclipse.birt.report.engine.emitter.prototype.excel/src/org/eclipse/birt/report/engine/emitter/excel/layout/ExcelLayoutEngine.java
Labels: BugFix

#1875 Fix the maximum size of a word page and set the size to max value 22in (#1874)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
Labels: BugFix

#1865 Enhance the hyperlink text decoration option to enable/disable the default style handling (#1864)
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/page/DataPage.java
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/page/LabelPage.java
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/provider/FontStylePropertyDescriptorProvider.java
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/providers/AttributeValueConstant.java
  UI/org.eclipse.birt.report.designer.ui/icons/obj16/hyperlink-style-none.gif
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/IReportGraphicConstants.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/ReportPlatformUIImages.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/views/attributes/providers/AttributeConstant.java
  engine/org.eclipse.birt.report.engine.emitter.html.tests/test/org/eclipse/birt/report/engine/emitter/html/StyleTest.java
  engine/org.eclipse.birt.report.engine.emitter.html.tests/test/org/eclipse/birt/report/engine/emitter/html/html_report_gold.txt
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
  engine/org.eclipse.birt.report.engine.emitter.ppt/src/org/eclipse/birt/report/engine/emitter/ppt/util/PPTUtil.java
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/HyperlinkInfo.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/TOCStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/script/instance/IScriptStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/IStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/dom/AbstractStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/BIRTPropertyManagerFactory.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/PerfectHash.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/README.md
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/StyleConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/birt/BIRTConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/css/CSSConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/css/CSSValueConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/css/TextHyperlinkManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextAreaLayout.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/style/TextStyle.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/EngineIRVisitor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/StylePropertyMapping.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/StyleUtil.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/script/internal/instance/StyleInstance.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/BirtStyle.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/FontManager.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/StyleHandle.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/elements/DesignChoiceConstants.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IStyleModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/IDesignSchemaConstants.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/VersionUtil.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/ModuleWriterImpl.java
  xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/script/internal/StyleInstance.java
Labels: Feature
