Repository eclipse-birt/birt, pull requests merged in 2024-07, with the labels that each got.

#1777 Remove *.product files that are not actually used to build products
  UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
  UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
  UI/org.eclipse.birt.report.designer.ui.rcp/build.properties
  build/birt-packages/birt-report-all-in-one/BIRT.product
  build/org.eclipse.birt.target/org.eclipse.birt.target.target
  engine/org.eclipse.birt.report.engine/ReportEngineSDK.product
  engine/org.eclipse.birt.report.engine/sdk/config.ini
Labels: Dependencies

#1780 Remove the deprecated security manager and add a JVM-birt system property for activation (#1778)
  core/org.eclipse.birt.core/src/org/eclipse/birt/core/script/JavascriptEvalUtil.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngine.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngineFactory.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptVersion.java
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/README.md
  data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/ScriptUtil.java
Labels: BugFix

#1786 Remove console output messages (#1753)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
Labels: BugFix

#1788 Enhance the property for the excel emitter (#1787)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/EmitterServices.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: Enhancement

#1789 Enhance the designer properties for the excel emitter (part 3, #1770)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/EmitterServices.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportDesignModel.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/DesignWriterImpl.java
Labels: Enhancement

#1798 Fix the index out of bound exception of rank calculation (#1797)
  data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/BaseTotalRank.java
Labels: BugFix

#1803 Reorganization of the excel README.MD to have an alphabetic property order and enhance documentation details
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
Labels: Documentation

#1805 Change parameter encoding from 8859-1 to UTF-8 (#1800)
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/filter/ViewerFilter.java
Labels: BugFix

#1811 Excel emitter avoid null pointer exception of merged rows with image (#1810)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
Labels: BugFix

#1813 Fix html table processor to validate the node type (#1812)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/TableProcessor.java
Labels: BugFix

#1739 Show the DataView when a new report is created #1738
  UI/org.eclipse.birt.report.designer.ui.ide/src/org/eclipse/birt/report/designer/ui/ide/wizards/NewReportWizard.java
Labels: Enhancement

#1814 Enhance comments, raw types and other small hints to reduce java warnings
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/TableProcessor.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/DesignElementHandle.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ErrorDetail.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java
Labels: Dependencies, Documentation

#1821 Reduce org.eclipse.birt.engine.runtime content
  build/birt-packages/birt-runtime-osgi/reportengine.product
  features/org.eclipse.birt.chart.osgi.runtime/feature.xml
  viewer/org.eclipse.birt.report.viewer/META-INF/MANIFEST.MF
Labels: Dependencies
