Repository eclipse-birt/birt, pull requests merged in 2024-09, with the labels that each got.

#1883 Enhance JavaScript syntax highlighter (#1882)
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
Labels: Enhancement

#1884 Added java doc comments for JavaScript constants (#1882)
  data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/script/ScriptConstants.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/script/element/IReportItem.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/simpleapi/IReportItem.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/simpleapi/ScriptConstants.java
Labels: Documentation

#1896 Add margin handling to the element "Label" (#1895)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
Labels: Enhancement

#1900 Fix the doubled margin calculation of text elements (foreign text)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/DocxEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/DocWriter.java
Labels: BugFix

#1904 The preview does not work anymore: #1901
  UI/org.eclipse.birt.report.designer.ui.preview.static_html/src/org/eclipse/birt/report/designer/ui/viewer/StaticHTMLViewer.java
  UI/org.eclipse.birt.report.designer.ui.preview/plugin.properties
  UI/org.eclipse.birt.report.designer.ui.preview/src/org/eclipse/birt/report/designer/ui/preview/editors/ReportPreviewFormPage.java
Labels: Enhancement, BugFix

#1906 Fix DOCX font size converting issue (#1905)
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/BasicComponent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/HTMLTags.java
Labels: BugFix

#1923 Fix NPE if string for crop overflow is null (#1921)
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
Labels: BugFix

#1925 Embed-tag for svg-images, avoid event-forwarding if hyperlink is in use (#1924)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/HTMLTags.java
Labels: Enhancement
