Repository eclipse-birt/birt, pull requests merged in 2025-05, with the labels that each got.

#2136 Enhance html report viewer with dark-light-theme layout (#2135)
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/core/BirtCommunicationManager.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/core/BirtEvent.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbarTheme.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/report/BirtReportDocument.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Close.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Error.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/control/ToolbarFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/ExceptionDialogFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/layout/FramesetFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/dialogbase.css
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/dialogbase_rtl.css
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/style.css
Labels: Enhancement

#2138 Enhance html report viewer optimized icons (#2137)
  UI/org.eclipse.birt.report.designer.ui.preview.static_html/src/org/eclipse/birt/report/designer/ui/preview/static_html/StaticHTMLPrviewPlugin.java
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtNavigationBar.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/dialog/BirtSimpleExportDataDialog.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Add.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/AddAll.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/AddAll_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/AddAll_rtl.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/AddAll_rtl_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Add_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Add_rtl.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Add_rtl_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Down.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Down_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/FirstPage.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/FirstPage_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Go.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Go_rtl.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/LastPage.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/LastPage_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/NextPage.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/NextPage_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/PreviousPage.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/PreviousPage_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Remove.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/RemoveAll.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/RemoveAll_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/RemoveAll_rtl.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/RemoveAll_rtl_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Remove_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Remove_rtl.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Remove_rtl_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Up.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Up_disabled.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/control/NavigationbarFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/style.css
Labels: Enhancement

#2140 Fix xlsx column width auto default if width is unset (#2139)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManager.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
Labels: BugFix

#2141 Enhance pdf glyph substitution handling (#2133)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
Labels: Enhancement

#2142 Enhance report viewer dark theme background (#2135)
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbarTheme.js
Labels: Enhancement

#2146 Fix html preview to display empty header and footer correctly (#2145)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
Labels: BugFix

#2147 Enhance on designer master page with vertical display of header/footer options
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/page/HeaderFooterPage.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/util/WidgetUtil.java
Labels: Enhancement, Documentation

#2154 Add new info dialog and enhance dialog layout (#2149)
  UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/section/CheckSection.java
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-template.xml
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-viewer.xml
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-war.xml
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web.xml
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web_deploy.xml
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbar.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbarTheme.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/dialog/AbstractBaseDialog.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/images/Info.png
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/control/ToolbarFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/DialogContainerFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/dialogbase.css
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/dialogbase_rtl.css
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/style.css
Labels: Enhancement

#2156 Fix the click handling of html viewer dialogs (#2155)
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/resource/Messages.properties
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/BirtUtility.java
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/control/NavigationbarFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/control/ToolbarFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/ParameterDialogFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/PrintReportServerDialogFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/style.css
Labels: BugFix

#2159 Enhance viewer dialogs with added escape key for closing (#2157)
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/utility/BirtUtility.js
Labels: Enhancement

#2160 Optimize viewer button page layout preview (#2132)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/taglib/ParamDefTag.java
Labels: Enhancement

#2164 Latest com.github.librepdf.openpdf needs bcpkix
  build/org.eclipse.birt.target/org.eclipse.birt.target.target
  engine/org.eclipse.birt.report.engine/META-INF/MANIFEST.MF
Labels: Releng

#2166 Enhance data export dialog csv with options for column name export (#2165)
  engine/org.eclipse.birt.report.engine.dataextraction.csv/src/org/eclipse/birt/report/engine/dataextraction/csv/CSVDataExtractionImpl.java
  engine/org.eclipse.birt.report.engine.dataextraction/src/org/eclipse/birt/report/engine/dataextraction/CSVDataExtractionOption.java
  engine/org.eclipse.birt.report.engine.dataextraction/src/org/eclipse/birt/report/engine/dataextraction/CommonDataExtractionOption.java
  engine/org.eclipse.birt.report.engine.dataextraction/src/org/eclipse/birt/report/engine/dataextraction/ICSVDataExtractionOption.java
  engine/org.eclipse.birt.report.engine.dataextraction/src/org/eclipse/birt/report/engine/dataextraction/ICommonDataExtractionOption.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/DataExtractionOption.java
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/resource/Messages.properties
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/DataExtractionParameterUtil.java
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/dialog/BirtSimpleExportDataDialog.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/utility/Constants.js
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/SimpleExportDataDialogFragment.jsp
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/styles/style.css
Labels: Enhancement

#2167 Enhance dark theme cookie with expiration time
  viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbarTheme.js
Labels: Enhancement

#2172 Synchronize System.getProperties() access
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SecurityUtil.java
Labels: BugFix
