Repository eclipse-birt/birt, pull requests merged in 2025-02, with the labels that each got.

#2047 Changes to improve the background image handling of SVG for the designer (#2046)
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editparts/ReportElementEditPart.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/PropertyUtil.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/style/BackgroundImageInfo.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SvgFile.java
Labels: BugFix

#2050 Enhance the output to support image option "fit to container" for HTML-preview and DOCX (#2025)
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLPerformanceOptimize.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/IImageContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/ImageContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ImageItemExecutor.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/internal/content/wrap/ImageContent.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/ir/ImageItemDesign.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/emitter/ImageLayout.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/util/DimensionUtil.java
Labels: Enhancement

#2053 Added java doc and remove warning of dimensions (#2050)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/ir/DimensionType.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/parser/EngineIRVisitor.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/util/StringUtil.java
Labels: Documentation

#2056 Enhance dimension utility and add pixel converting (#2055)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLPerformanceOptimize.java
  model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/util/DimensionUtilTest.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/util/DimensionUtil.java
Labels: Enhancement

#2060 Fix issue 2057: Take letter-spacing into account for width calculation
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextArea.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextCompositor.java
Labels: BugFix

#2059 Enhance the PDF glyph handling to handle advanced kerning and ligatures (#2058)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
  engine/org.eclipse.birt.report.engine.fonts/fontsConfig.xml
  engine/org.eclipse.birt.report.engine.fonts/fontsConfig_pdf.xml
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontConfigHandler.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontConfigReader.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontHandler.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingConfig.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingManager.java
Labels: Enhancement
