Repository eclipse-birt/birt, pull requests merged in 2025-03, with the labels that each got.

#2068 Fix docx header issue #2026
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Document.java
  engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
  engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/DocWriter.java
Labels: BugFix

#2070 Enhance font classes to set types at collections and maps and add java-doc (#2069)
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/CharSegment.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/CompositeFont.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/CompositeFontConfig.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontCacheUtils.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontConfigHandler.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingManager.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingManagerFactory.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontSplitter.java
Labels: BugFix, Documentation

#2088 Fix HTML-preview to improve the table display without width-values (#2087)
  engine/org.eclipse.birt.report.engine.emitter.html.tests/test/org/eclipse/birt/report/engine/emitter/html/html_report_gold.txt
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
Labels: BugFix

#2086 Enhance the handling of merged cell content to divide between table and text content (#2085)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
Labels: Enhancement

#2096 Fix pptx image without link/bookmark to avoid NullPointerException (#2095)
  engine/org.eclipse.birt.report.engine.emitter.ppt/src/org/eclipse/birt/report/engine/emitter/ppt/util/PPTUtil.java
  engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
Labels: BugFix

#2094 Fix HTML preview if an image is outside of a table/grid (#2093)
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLPerformanceOptimize.java
Labels: BugFix

#2097 Remove the change of display attribute due to side effects (#2087)
  engine/org.eclipse.birt.report.engine.emitter.html.tests/test/org/eclipse/birt/report/engine/emitter/html/html_report_gold.txt
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
  engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
Labels: BugFix

#2098 Restore the original handling of nested tables (#2085)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
Labels: BugFix

#2099 Fix excel auto size of column width setting
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
Labels: BugFix

#2101 Implement ability to search in outline
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/util/IHelpContextIds.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/DefaultNodeProvider.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/SearchInputDialog.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/actions/SearchAction.java
Labels: Feature

#2103 Fix NPE of date parsing at usage of DateFormatISO8601 (#2102)
  core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DateFormatISO8601.java
Labels: BugFix

#2104 Enhance outline search dialog 2101
  UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/SearchInputDialog.java
  UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/actions/SearchAction.java
  model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/core/DesignElement.java
Labels: Enhancement

#2108 Enhance excel utilities with method to calculate the point height for an excel-row based on unit millimeters
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ClientAnchorConversions.java
Labels: Enhancement

#2109 Optimized naming and documentation of complex font handling for PDF (#2107)
  engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontConfigHandler.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontHandler.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingConfig.java
  engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingManager.java
Labels: Documentation
