Repository eclipse-birt/birt, pull requests merged in 2025-04, with the labels that each got.

#2112 Fix the excel output for multiple cell entries with user property ExcelEmitter.ValueAsFormula (#2111)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
Labels: BugFix

#2116 Fix excel row vertical alignment (#2114)
  engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
Labels: BugFix

#2118 Fix viewer locale and optimize the locale validation (#2115)
  viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java
Labels: BugFix

#2124 Add documentation links to the birt application page (#2123)
  viewer/org.eclipse.birt.report.viewer/birt/index.jsp
Labels: Enhancement, Documentation

#2125 Enhance documentation of font configuration
  engine/org.eclipse.birt.report.engine.fonts/README.md
  engine/org.eclipse.birt.report.engine.fonts/fontsConfig.xml
  engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/layout/pdf/font/FontHandlingPdfTest.java
Labels: Documentation

#2128 Update *.aggr for Maven publishing
  build/org.eclipse.birt.releng.maven/BIRT-Runtime-Minimized.aggr
  build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggr
Labels: Releng

#2130 Add new link to font configuration README.MD (#2125)
  engine/org.eclipse.birt.report.engine.fonts/README.md
  viewer/org.eclipse.birt.report.viewer/birt/index.jsp
Labels: Documentation
